[package]
name = "command"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.69"
quote = "1.0.36"
proc-macro2 = "1.0.86"
heck = "0.5.0"
regex = "1.10.5"
regex-split = "0.1.0"
